spring:
  application:
    name: mongo
  data:
    mongodb:
      uri: mongodb+srv://curso_babel:KHGRPbbsJQO1ydWQ@mongodbtutorial.8jtrz8r.mongodb.net?appName=MongoDbTutorial
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG